name: stream_archive
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Connectivity
  http: ^1.2.1
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html: ^0.15.1
  flutter_html_table: ^3.0.0-beta.2
  flutter_super_html_viewer: ^0.1.0
  html: ^0.15.4
  flutter_inappwebview: ^6.0.0
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  path_provider: ^2.0.9
  file_picker: ^8.0.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  js: ^0.6.2
  shared_preferences: ^2.0.11
  intl: ^0.18.1
  pull_to_refresh: ^2.0.0
  iconsax: ^0.0.8
  animated_toggle: ^0.1.3
  toggle_switch: ^2.3.0
  font_awesome_icon_class: ^0.0.6
  connectivity_plus: ^6.1.2
  loading_animation_widget: ^1.2.1
  multi_select_flutter: ^4.1.3
  negative_padding: ^0.0.1
  stack_trace: ^1.11.1
  path: ^1.8.0
  #  signalr_netcore: ^0.1.6+1
  flutter_launcher_icons: ^0.13.1
  loader_overlay: ^4.0.0
  line_awesome_flutter: ^3.0.1
  dropdown_button2: ^1.4.0
  url_launcher: ^6.1.8
  webview_flutter: ^4.0.1
  #  flutter_webview_plugin: ^0.4.0
  pdfx: ^2.6.0
  #  file_previewer: ^0.1.0
  flutter_pdfview: ^1.3.2
  webview_flutter_plus: ^0.4.5
  video_player: ^2.5.1
  audioplayers: ^6.0.0
  animated_icon: ^0.0.9
  #  html_editor_enhanced: ^2.6.0
  #  flutter_quill: ^9.3.3
  vsc_quill_delta_to_html: ^1.0.5
  search_page: ^2.3.0
  #  quill_delta: ^3.0.0-nullsafety.0
  html_unescape: ^2.0.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_slidable: ^3.1.1
  icon_decoration: ^2.0.2
  material_symbols_icons: ^4.2785.1
  jumping_dot: ^0.0.7
  signature: ^5.5.0
#  open_document: ^1.0.7
  #  internet_connection_checker_plus: ^2.5.2
  #  signalr_flutter: ^0.2.0
  get: ^4.6.6
  web_socket_channel: ^2.1.0
  signalr_core: ^1.1.2
  flutter_local_notifications: ^18.0.1
  flutter_background_service: ^5.0.10
  uuid: ^4.5.1
  #  background_fetch: ^1.3.7
  workmanager: ^0.5.2
  firebase_core: ^2.0.0
  firebase_messaging: ^14.9.4
  #  flutterfire_cli: ^1.0.0
  win32: ^5.8.0
  #  flutter_background: ^1.2.0
  #  awesome_notifications: ^0.8.2
  photo_view: ^0.14.0

  graphite: ^1.2.0
  bcrypt: ^1.1.3
  mime: ^2.0.0
  dio: ^5.8.0+1
  flutter_image_compress: ^2.0.3
  syncfusion_flutter_pdf: ^28.1.33
  syncfusion_flutter_charts: ^28.2.5+1
  pdf_render: ^1.4.12
#  flutter_document_picker: ^5.2.3
  flutter_file_dialog: ^3.0.2
  excel: ^4.0.6
  flutter_widget_to_image: ^0.0.1
  screenshot: ^3.0.0
  image: ^4.3.0
  syncfusion_flutter_xlsio: ^28.1.33
  cross_file: ^0.3.4+2
  flutter_image: ^4.1.12
  archive: ^3.3.7
  google_mlkit_text_recognition: ^0.13.0
  pdf: ^3.10.4
  azure_blob_flutter: ^0.0.9
  azblob: ^4.0.0
  xml: ^6.5.0
  hijri: ^3.0.0
  open_file: ^3.3.2





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/logo_images/archive_below_logo.png
   - assets/logo_images/archive_dbl_above_logo.png
   - assets/svg_icons/archive_favorite_icon.svg
   - assets/svg_icons/archive_inbox_icon.svg
   - assets/svg_icons/archive_share_with_me_icon.svg
   - assets/svg_icons/archive_shared_expired_icon.svg
   - assets/svg_icons/archive_trash_icon.svg
   - assets/svg_icons/share_by_me_archive_icon.svg
   - assets/defaultThumbnail.png
   - assets/svg_icons/inbox_icon.svg
   - assets/svg_icons/announcement_icon.svg
   - assets/svg_icons/attachment_icon.svg
   - assets/svg_icons/delete_icon.svg
   - assets/svg_icons/draft_icon.svg
   - assets/svg_icons/favorite_icon.svg
   - assets/svg_icons/pending_from_others_icon.svg
   - assets/svg_icons/pin_icon.svg
   - assets/svg_icons/send_icon.svg
   - assets/svg_icons/share_icon.svg
   - assets/svg_icons/unread_icon.svg
   - assets/svg_icons/trash_icon.svg
   - assets/svg_icons/label_icon.svg
   - assets/svg_icons/pin_filled_icon.svg
   - assets/svg_icons/filled_bookmark_icon.svg
   - assets/svg_icons/search_icon.svg
   - assets/svg_icons/edit_icon.svg
   - assets/svg_icons/workflow_icon.svg
   - assets/svg_icons/cloud_upload_icon.svg
   - assets/svg_icons/XSL.svg
   - assets/svg_icons/PDF.svg
   - assets/svg_icons/DOCX.svg
   - assets/svg_icons/DOCc.svg
   - assets/svg_icons/DOC.svg
   - assets/svg_icons/AI.svg
   - assets/svg_icons/AVI.svg
   - assets/svg_icons/JPG.svg
   - assets/svg_icons/MP3.svg
   - assets/svg_icons/MP4.svg
   - assets/svg_icons/PPT.svg
   - assets/svg_icons/PS.svg
   - assets/svg_icons/PSD.svg
   - assets/svg_icons/SVG.svg
   - assets/svg_icons/ZIP.svg
   - assets/svg_icons/reply_icon.svg
   - assets/svg_icons/replyall_icon.svg
   - assets/svg_icons/forward_icon.svg
   - assets/svg_icons/cancel_icon.svg
   - assets/svg_icons/approve_icon.svg
   - assets/svg_icons/PNG.svg
   - assets/svg_icons/workflow_list_icon.svg
   - assets/svg_icons/stream_box_icon.svg
   - assets/svg_icons/cabinate_icon.svg
   - assets/bar-code.PNG

